src/Entity/Films.php
<?php

namespace App\Entity;

use App\Repository\FilmsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use DateTime;
use Symfony\Component\Validator\Constraints as assert;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmsRepository::class)
 */
class Films
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $director;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Seance::class, mappedBy="films")
     */
    private $seance;


    public function __construct()
    {
        $this->seance = new ArrayCollection();
        $this->seances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(?string $director): self
    {
        $this->director = $director;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Seance>
     */
    public function getSeance(): Collection
    {
        return $this->seance;
    }

    public function addSeance(Seance $seance): self
    {
        if (!$this->seance->contains($seance)) {
            $this->seance[] = $seance;
            $seance->setFilms($this);
        }

        return $this;
    }

    public function removeSeance(Seance $seance): self
    {
        if ($this->seance->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getFilms() === $this) {
                $seance->setFilms(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Seance>
     */
    public function getSeances(): Collection
    {
        return $this->seances;
    }
}

src/Entity/Salle.php
<?php

namespace App\Entity;

use App\Entity\Seance;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SalleRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=SalleRepository::class)
 */
class Salle
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Numero;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\OneToMany(targetEntity=Seance::class, mappedBy="salle")
     */
    private $seances;

    public function __construct()
    {
        $this->seances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?int
    {
        return $this->Numero;
    }

    public function setNumero(int $Numero): self
    {
        $this->Numero = $Numero;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, Seance>
     */
    public function getSeances(): Collection
    {
        return $this->seances;
    }

    public function addSeance(Seance $seance): self
    {
        if (!$this->seances->contains($seance)) {
            $this->seances[] = $seance;
            $seance->setSalle($this);
        }

        return $this;
    }

    public function removeSeance(Seance $seance): self
    {
        if ($this->seances->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getSalle() === $this) {
                $seance->setSalle(null);
            }
        }

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Films;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, ["required" => true])
            ->add('director', TextType::class)
            ->add('duree', IntegerType::class)
            ->add('save', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Films::class,
        ]);
    }
}

src/Controller/FilmsController.php
<?php

namespace App\Controller;

use App\Entity\Films;
use App\Form\FilmType;
use App\Repository\SeanceRepository;
use DateTimeImmutable;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FilmsController extends AbstractController
{
    /**
     * @Route("/createFilm", name="create_film")
     * @Route("/updateFilm/{id?1}", name="update_film")
     */
    public function index(Films $film = null, Request $request, ManagerRegistry $doctrine)
    {
        $entityManager = $doctrine->getManager();

        $isEditor = false;
        if (!$film) {
            $film = new films;
        }

        $form = $this->createForm(FilmType::class, $film);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$film->getId()) {
                $film->setCreatedAt(new DateTimeImmutable());
            }

            $film = $form->getData();
            $entityManager->persist($film);
            $entityManager->flush();

            return $this->redirectToRoute('ListingFilms');
        }
        return $this->render("films/form.html.twig", [
            'form' => $form->createView(),
            'isEditor' => $film->getId(),
            'errors=>$errors'
        ]);
    }
    /**
     * @Route("/ListingFilms", name="ListingFilms")
     */
    public function listing(ManagerRegistry $doctrine): Response
    {
        $films = $doctrine->getManager()->getRepository(Films::class)->findAll();

        return $this->render('films/films.html.twig', ["films" => $films]);
    }
    /**
     * @Route("/{id}", name="film_show", methods={"GET"})
     */
    public function show(Films $film): Response
    {
        return $this->render('films/show.html.twig', [
            'film' => $film,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="deleteFilm")
     */
    public function delete(Films $film): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        if (isset($film)) {
            $listSeances = $film->getSeance();
            foreach ($listSeances as $Seance) {
                $entityManager->remove($Seance);
            }
            $entityManager->remove($film);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ListingFilms');
    }

    /**
     * @Route("/film/edit/{id}")
     */
    public function update(int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $Film = $entityManager->getRepository(Films::class)->find($id);

        if (!$Film) {
            throw $this->createNotFoundException(
                'No Film found for id ' . $id
            );
        }

        $Film->setTitle('New Film name!');
        $entityManager->flush();

        return $this->redirectToRoute('product_show', [
            'id' => $Film->getId()
        ]);
    }
}

templates/films/_delete_form.html.twig
<form method="post" action="{{ path('deleteFilm', {'id': film.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn">Delete</button>
</form>

templates/films/create.html.twig
{% extends "base.html.twig"%}
{% block title %}
	{% if (isEditor) %}
		modifier film
	{% else %}
		Ajout film
	{% endif %}
{% endblock %}
{% block body %}
	{{ form(form) }}{% endblock %}

templates/films/films.html.twig
{% extends "base.html.twig" %}
{% block body %}
	<div>
	<h1>	Liste des films à l'écran</h1></div>
	{% if films|length ==0 %}
		pas de films disponibles
	{% endif %}
	<table class="table">
		{% for film in films%}
		<tr>
		<td>
			
			{{film.getTitle()}}
	
	
	</td>
	<td>
                    <a href="{{ path('film_show', {'id': film.id}) }}">show</a>
                    <a href="{{ path('update_film', {'id': film.id}) }}">edit</a>
		
    	</td>
	</tr>
		{% endfor %}
		</table>
		  <a href="{{ path('create_film') }}">Create new</a>
{% endblock %}

templates/films/form.html.twig
 {% extends 'base.html.twig' %}

{% block title %}CINEMA TONIO{% endblock %}

{% block body %}
 {% if (isEditor) %}
        <div>Formualire de modification de film</div>
    {% else %}
        <div>Formualire d'ajout de film</div>
    {% endif %}
    {{ form_start(form) }}

    <div class='mb-10'>
        {{ form_row(form.title, { 'label': 'Title :' }) }}
    </div>

    <div class='mb-10'>
        {{ form_row(form.director, { 'label': 'Réalisateur :' }) }}
    </div>
     <div class='mb-10'>
        {{ form_row(form.duree, { 'label': 'Durée en minutes :' }) }}
    </div>
     <div>
        {% if (isEditor) %}
            {{ form_row(form.save, { 'label': 'Edit :' }) }}
        {% else %}
            {{ form_row(form.save, { 'label': 'Save :' }) }}
        {% endif %}
    </div>

    {{ form_end(form) }}
{% endblock %}

templates/films/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FilmsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/project_symfony/src/Controller/FilmsController.php'|file_link(0) }}">src/Controller/FilmsController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/project_symfony/templates/films/index.html.twig'|file_link(0) }}">templates/films/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/films/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film{% endblock %}

{% block body %}
    <h1>Film</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ film.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ film.title }}</td>
            </tr>
                        <tr>
                <th>Réalisateur</th>
                <td>{{ film.director }}</td>
            </tr>
              </tr>
                        <tr>
                <th>Durée</th>
                <td>{{ film.duree }} min</td>
            </tr>
            <tr>
                <th>CreateAt</th>
                <td>{{ film.createdAt ? film.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
              <tr>
                <th>Séances</th>
                
                {% if film.getSeance()|length ==0%}
                <tr>
		          <td>  pas de Séances disponibles</td>
                    </tr>
	            {% endif %}
                
                {% for seance in film.getSeance()%}
                <tr>
                 <td>{{seance.dateDebut ? seance.dateDebut|date('Y-m-d H:i') : ''}}</td>
                <td>en {{seance.langue}}</td>
                  <td>en salle {{seance.getSalle().numero}} ({{seance.getSalle().nom}})</td>
                </tr>
                {% endfor %}
            </tr>
        </tbody>
    </table> 

    <a href="{{ path('ListingFilms') }}">back to list</a>

    <a href="{{ path('update_film', {'id': film.id}) }}">edit</a>

    {{ include('films/_delete_form.html.twig') }}
{% endblock %}